### ISSUE TITLE
Shared stahes

### ISSUE THREAD

**Issue by Boikevi4** [akiroth/Outward#1]
Hey there! Sorry for disturbing but can you please do shared stashes for co-op split screen in Outward DE like it was in default game. This mod that you did (MustStashes) is awesome but it can open stash everywhere and need a buttom to activate it. But can you do like it was in default game (2 players have same stash and open it only near stash) pretty please. Thank you!

**Comment by akiroth** [comment]
Created a new mod "HostOnlyStash" that changes the default opening of the stashes to only open the world host's stash.  Tested in split screen but not online play.

Debugging the 'MustStash' mod for an issue but I am also adding a config option for host only (updating config descriptions since 'only in towns' was already an available option).

**Comment by Boikevi4** [comment]
Thank You a lot!!!
